# Generated by Django 4.2 on 2024-04-06 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(db_column='acc_id', primary_key=True, serialize=False)),
                ('acc_name', models.CharField(max_length=16)),
                ('acc_type', models.CharField(choices=[('Credit', 'Credit'), ('Savings', 'Savings')], default='Savings', max_length=16)),
                ('acc_description', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conf_account',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.AutoField(db_column='cat_id', primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=64)),
                ('cat_description', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conf_categories',
            },
        ),
        migrations.CreateModel(
            name='GroupExpenses',
            fields=[
                ('group_exp_id', models.AutoField(db_column='gp_exp_id', primary_key=True, serialize=False)),
                ('group_expense_desc', models.CharField(max_length=256)),
                ('expense_amount', models.FloatField()),
                ('number_of_users', models.IntegerField()),
                ('amount_per_user', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account', on_delete=django.db.models.deletion.CASCADE, to='expenses.account')),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='expenses.categories')),
            ],
            options={
                'db_table': 'group_expenses',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(db_column='group_id', primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=16)),
                ('group_description', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conf_group',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('sub_cat_id', models.AutoField(db_column='sub_cat_id', primary_key=True, serialize=False)),
                ('sub_cat_name', models.CharField(max_length=64)),
                ('sub_cat_description', models.CharField(blank=True, max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='expenses.categories')),
            ],
            options={
                'db_table': 'conf_sub_categories',
            },
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('group_user_id', models.AutoField(db_column='group_user_id', primary_key=True, serialize=False)),
                ('group', models.ForeignKey(db_column='group', on_delete=django.db.models.deletion.CASCADE, to='expenses.groups')),
                ('member', models.ForeignKey(db_column='member', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conf_group_members',
            },
        ),
        migrations.CreateModel(
            name='GroupExpenseUsers',
            fields=[
                ('group_expense_user_id', models.AutoField(db_column='gp_exp_user_id', primary_key=True, serialize=False)),
                ('group_exp', models.ForeignKey(db_column='group_exp', on_delete=django.db.models.deletion.CASCADE, to='expenses.groupexpenses')),
                ('group_exp_user', models.ForeignKey(db_column='group_exp_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_expense_users',
            },
        ),
        migrations.AddField(
            model_name='groupexpenses',
            name='sub_category',
            field=models.ForeignKey(blank=True, db_column='sub_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.subcategories'),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.AutoField(db_column='exp_id', primary_key=True, serialize=False)),
                ('expense_desc', models.CharField(db_column='exp_desc', max_length=16)),
                ('expense_type', models.CharField(choices=[('Single', 'Single'), ('Group', 'Group')], default='Single', max_length=8)),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account', on_delete=django.db.models.deletion.CASCADE, to='expenses.account')),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='expenses.categories')),
                ('group_expense', models.ForeignKey(db_column='group_expense', on_delete=django.db.models.deletion.CASCADE, to='expenses.groupexpenses')),
                ('sub_category', models.ForeignKey(blank=True, db_column='sub_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.subcategories')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
    ]
