# Generated by Django 4.2 on 2024-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IvAccount',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_name', models.CharField()),
            ],
            options={
                'db_table': 'iv_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvConfGoal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField()),
            ],
            options={
                'db_table': 'iv_conf_goal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvConfMf',
            fields=[
                ('conf_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField()),
                ('fund_code', models.CharField(blank=True, null=True)),
                ('category', models.CharField(blank=True, null=True)),
                ('sub_category', models.CharField(blank=True, null=True)),
                ('market_cap', models.CharField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, null=True)),
                ('curr_val', models.FloatField(blank=True, null=True)),
                ('lock_in', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iv_conf_mf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvConfNps',
            fields=[
                ('conf_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'iv_conf_nps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvConfPf',
            fields=[
                ('conf_id', models.AutoField(primary_key=True, serialize=False)),
                ('pf_type', models.CharField()),
                ('lock_in', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iv_conf_pf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvConfSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField()),
            ],
            options={
                'db_table': 'iv_conf_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvConfStock',
            fields=[
                ('conf_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField()),
                ('stock_code', models.CharField()),
                ('market_cap', models.CharField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, null=True)),
                ('ipo', models.BooleanField(blank=True, null=True)),
                ('curr_val', models.FloatField(blank=True, null=True)),
                ('lock_in', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iv_conf_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvTxnCombined',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('invested_amount', models.FloatField(blank=True, null=True)),
                ('current_amount', models.FloatField(blank=True, null=True)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('pnl_percent', models.FloatField(blank=True, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('free_units', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iv_txn_combined',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvTxnMf',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('invested_amount', models.FloatField(blank=True, null=True)),
                ('units', models.FloatField(blank=True, null=True)),
                ('nav', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iv_txn_mf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvTxnStock',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('invested_amount', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iv_txn_stock',
                'managed': False,
            },
        ),
    ]
